name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main # Change this if needed

jobs:
  build:
    runs-on: windows-latest # Run on Windows to generate a Windows executable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile TWRankings.py  # Replace with your script name

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/TWRankings.exe # Replace with the correct output name

      - name: Commit and push EXE back to the repository
        run: |
          git config --global user.name "github-actions"  
          git config --global user.email "actions@github.com"  
          git add dist/TWRankings.exe  
          git commit -m "Add built executable"  
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
