name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main # Trigger on push to the main branch

  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Allow pushing content changes

jobs:
  build:
    runs-on: windows-latest # Run on Windows to generate EXE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd TribalWars/Staff-Scripts/TWRankings  # Move to the directory where the script is
          python -m pip install --upgrade pip  
          pip install pyinstaller

      - name: Build executable
        run: |
          cd TribalWars/Staff-Scripts/TWRankings  # Move to the directory where the script is
          pyinstaller --onefile --console --hidden-import=PIL --clean TWRankings.py  # Build the EXE

      - name: Debug - Check if EXE was created
        run: |
          cd TribalWars/Staff-Scripts/TWRankings  # Move to the directory where the script is
          echo "Checking dist/ directory..."
          dir dist  # List contents of dist/ folder to confirm EXE is created

      - name: Commit and push EXE if it exists
        run: |
          cd TribalWars/Staff-Scripts/TWRankings  # Move to the directory where the script is
          if (Test-Path dist\TWRankings.exe) {
            echo "EXE found, committing..."
            git config --global user.name "github-actions"  
            git config --global user.email "actions@github.com"  
            git add dist/TWRankings.exe  
            git commit -m "Add built executable"  
            git push https://github.com/${{ github.repository }}.git HEAD:main
          } else {
            echo "ERROR: EXE not found!"
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
